MESSAGE(NoValueForArgument, "no value for argument")
MESSAGE(NonMultiUsedMultipleTimes, "a non-multi argument used multiple times")
MESSAGE(OptionFlagOverlapsHelp, "option flag overlaps help flag")
MESSAGE(OptionFlagsOverlap, "option flag overlaps")
MESSAGE(RequiredArgumentNotUsed, "required argument not used")
MESSAGE(FlagDoesNotHaveKeys, "flag does not have keys")
MESSAGE(MultiArgumentNotLast, "multi argument not last")
MESSAGE(
    RequiredNotConstructible,
    "required option or argument is not constructible")
MESSAGE(SubsequentParseCall, "subsequent parse call")
MESSAGE(ValueNotConvertibleToString, "value not convertible to string")
MESSAGE(OptionFlagDuplicated, "option flag is duplicated")
